- hosts: all
  tasks:
  - name: Install Prerequisites
    yum:
      name:
      - epel-release
      - vim
      - kernel
    register: yum
 
  - name: Disable SELinux
    selinux:
      state: disabled
    register: selinux
  
  - name: Reboot
    reboot:
      reboot_timeout: 600
    when: yum.changed or selinux.changed
  
  - name: Install PHP
    include_tasks: php.yml
  
  - name: Install Apache
    include_tasks: apache.yml
  
  - name: Install App
    include_tasks: app.yml
  
  - name: Install MySQL
    include_tasks: mysql.yml
  